name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install system dependencies
        run: |
          Rscript -e 'install.packages(c("pak"), repos = "https://cran.r-project.org")'
      - name: Restore dependencies
        run: |
          Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv"); renv::restore(prompt = FALSE)'
          Rscript -e 'source("dependencies.R"); if (exists("project_dependencies")) { if (requireNamespace("pak", quietly = TRUE)) pak::pkg_install(project_dependencies()); else install.packages(project_dependencies()); }'
      - name: Document
        run: Rscript -e 'if (requireNamespace("devtools", quietly = TRUE)) devtools::document()'
      - name: Check
        run: Rscript -e 'if (requireNamespace("devtools", quietly = TRUE)) devtools::check(error_on = "warning")'
